name: Build and deploy nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_PATH: 'RedisRepository/RedisRepository.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x 
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
        
    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      
    - name: Tag Repo
      uses: richardsimko/update-tag@v1
      with:
        tag_name: ${{ steps.gitversion.outputs.semVer }}
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_TOKEN }}

    - name: Build project
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: Pack project
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.gitversion.outputs.semVer }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: Push package
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_ORG_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}
